//
// Created by Maria on 25.01.2021.
//

#ifndef ROGUELIKE_CMAKE_BUILD_DEBUG_HEADERS_HELPERS_GAME_STATES_H_
#define ROGUELIKE_CMAKE_BUILD_DEBUG_HEADERS_HELPERS_GAME_STATES_H_

enum GameStates {
  ALIVE,
  DEAD,
  WINNER
};

#endif //ROGUELIKE_CMAKE_BUILD_DEBUG_HEADERS_HELPERS_GAME_STATES_H_
